### ISSUE TITLE
Can't capture handshake in kali 2016.2

### ISSUE THREAD

**Issue by evilpwn** [derv82/wifite#102]
use airodump-ng command can capture handshake,but wifite can't，and kali nethunter also can't capture，please help me!

**Comment by yzhkey** [comment]
my network is TL-WN722N

**Comment by KaliSentinelX** [comment]
I've tried with multiple wireless adapters and it happens both in nethunter and pwnie express phones :(

**Comment by KaliSentinelX** [comment]
@yzhkey  check this out https://github.com/kimocoder/wifite-ng

**Comment by kimocoder** [comment]
Well, just tested handshake capturing on wifite-ng and it works.. the problem guys, it that "wifite" is way outdated by now..

* WPS scanning is unstable + needs wash implementation fix for working again + check for LOCKED.
* tshark deps have changed, making it unavailable.
* reaver deps (options) have changed, resulting in reaver error
* macchanger/macaddr patch nedded
* Pyrit: Prevention of truncated handshakes 
* other scripts using aircrack-ng libs/tools needs an update to fit newest release

Many of these fixed are to be found at my GitHub repo, which KaliSentinelX commented.
We also need people with python + network libs experience to add new functions and keeping the tool alive for the future, feel free to tag team @ GitHub -- all help would be appreciated, so take a look on the TODO in the README.md whats planned.


**All credits still goes to "derv82" for giving us the best wifi tool out there.**

**Comment by derv82** [comment]
Should be fixed in https://github.com/derv82/wifite/commit/918a499786afdfefcc9582a29df79d0959294ba2

Sorry for the extremely long delay.
