### ISSUE TITLE
WPS PIN attack Never Initiates

### ISSUE THREAD

**Issue by theflarenet** [derv82/wifite#103]
Hi! I'm currently running wifite on `"Linux kali 4.4.32v7-aufs #1 SMP Fri Nov 18 23:17:35 CET 2016 armv7l GNU/Linux"` and I'm facing a small issue. The WPS PIN attack skips once I `CTRL+C` after the WPS Pixie attack:

```
 [+] 3 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): c
 [0:00:00] initializing WPS PIN attack on XXXXXX (XX:XX:XX:XX:XX:XX)
 [0:08:20] starting wpa handshake capture on "XXXXXX"
```

_*Note: SSID and MAC Address are obviously censored._

The WPS PIN attack works well when I use wifite in a virtual machine running on my mac but not on my Raspberry Pi. Any ideas?

**Comment by kimocoder** [comment]
theflarenet: wifite is kinda outdated, but you should try the more "up2date" fork of it @ https://github.com/kimocoder/wifite-ng

which is the exact same tool as wifite, but with fixes for several issues.

**ALL CREDITS TO DERV82 for making the best tool for wifi pentesting**

**Comment by methos2016** [comment]
they really should update the tool it was a nice program and less bs than the others  hate when cool tools just up and die




________________________________

**Comment by kimocoder** [comment]
I agree. I think it's the best one out there, fast, most attacks available & support for Android (NetHunter)

**Comment by pharonyk** [comment]
@kimocoder Thank you! I've visited that fork but found no instructions on how to install it nor any installer script. May I ask for simple instructions?

**Comment by theflarenet** [comment]
@kimocoder  Thank you! I've visited that fork but found no instructions on how to install it nor any installer script. May I ask for simple instructions?

**Comment by kimocoder** [comment]
git clone https://github.com/kimocoder/wifite-ng

then.. "cd wifite-ng" and do "chmod +x wifite-ng" and start it by running the command "./wifite-ng"

**Comment by theflarenet** [comment]
You've been a tremendous amount of help. Thank you!

**Comment by kimocoder** [comment]
Thanks for your kind works, just find me if you need help mister :)

**Comment by kimocoder** [comment]
** NOTICE: wifite-ng is now OUTDATED, please use derv82's original here instead (the code is cleaner and better too)

**Comment by pharonyk** [comment]
Thank you for the update again! You're great! 👍

**Comment by theflarenet** [comment]
Thank you for the update again! You're great! 👍

**Comment by kimocoder** [comment]
wifite & wifite2 has been updated, my fork "wifite-ng" is now the outdated one, so PLEASE use the original from derv82 again :)
