### ISSUE TITLE
WPS attack skipped

### ISSUE THREAD

**Issue by jensome101** [derv82/wifite#109]
When using the latest version provided with kali, the WPS attacks are being skipped and WPA handshake capture is started right away.

When using Kali 2017/01 without updating wifite, it still works.

The issue seems to have been introduced in the latest update for kali

**Comment by kimocoder** [comment]
wifite in Kali repos are outdated, git clone the repo for a more working version. (",)

**Comment by methos2016** [comment]
how about some one let kali no they need to update the repos so its one stop updates  for all the tools instead of bs having to re track working shit down all the time  wifite is a cool tool useful very very useful




________________________________

**Comment by kimocoder** [comment]
I do this all the time ;) most of the time they listen & some not. Check http://bugs.kali.org for more information

**Comment by kimocoder** [comment]
More specific @ https://bugs.kali.org/view.php?id=4051

**Comment by methos2016** [comment]
it be nice if it allowed you to select the #ber of dauths to send with a simple edit of the code with out having to edit all the code to do so..




________________________________

**Comment by kimocoder** [comment]
May also read the first post in Kali bug repos @ https://bugs.kali.org/view.php?id=4085

And maybe leave a comment for getting a faster update in their repos. Sadly, im on a long vecation without my computer and cant do much with anything.

**Comment by jensome101** [comment]
Works again in Kali, thanks
