### ISSUE TITLE
Wifite captures handshake but cap file is 0 bytes

### ISSUE THREAD

**Issue by JC-SoCal** [derv82/wifite#121]
[0:08:20] starting wpa handshake capture on "<redacted>"
 [0:03:51] new client found: <redacted>
 [0:03:03] listening for handshake...
 **[0:05:17] handshake captured! saved as "hs/<redacted>.cap"**

 [+] 1 attack completed:

 [+] 0/1 WPA attacks succeeded
        <redacted> (<redacted>) handshake captured
        saved as hs/<redacted>.cap

 [+] starting WPA cracker on 1 handshake
 [0:00:00] cracking <redacted> with aircrack-ng

 [!]crack attempt failed: passphrase not in dictionary

 [+] disabling monitor mode on wlan0mon... done
 [+] quitting

[2017-12-05-10:13:26] root@<redacted>:~# cd hs
[2017-12-05-10:13:29] root@<redacted>:~/hs# ls -lah
total 8.0K
drwxr-xr-x 2 root root 4.0K Dec  5 09:40 .
drwxr-xr-x 9 root root 4.0K Dec  5 09:40 ..
**-rw-r--r-- 1 root root    0 Dec  5 09:40 <redacted>.cap**

**Comment by kimocoder** [comment]
For handshake capture, the wifite2 works GREAT, but unfortunately it got problems in regular wifite (v1).

**Comment by JC-SoCal** [comment]
Sorry, I didn't know there was a wifite2, i'll close this issue. Thanks!
