### ISSUE TITLE
Wifite bug,  not work or has errore. 

### ISSUE THREAD

**Issue by azadoraha** [derv82/wifite#127]
[!] ERROR: wifite must be run as root
 [!] login as root (su root) or try sudo ./wifite.py
 
✘  ~/wifite   master   sudo python2 wifite.py
Failed to execute process '/data/data/com.termux/files/usr/bin/sudo'. Reason:
exec: Exec format error
The file '/data/data/com.termux/files/usr/bin/sudo' is marked as an executable but could not be run by the operating system.

**Comment by derv82** [comment]
This sounds like an issue with https://github.com/st42/termux-sudo -- not wifite. If you can't run `sudo` *at all* then it's definitely not a Wifite problem.

**Comment by chuotshin** [comment]
hello I just try to install sudo and it success

$ apt update
$ apt upgrade
$ apt install git
$ apt install tsu
$ git clone https://gitlab.com/st42/termux-sudo
$ cd termux-sudo
$ cat sudo > /data/data/com.termux/files/usr/bin/sudo
$ chmod 700 /data/data/com.termux/files/usr/bin/sudo
$ sudo su
$ sudo tsu
From Termux Guide APP, Just repalace the github with gitlab.

(I copy this on the internet)
MORE LINK IF YOU NEED: https://gist.github.com/GabrielMMelo/0e146f32d73978bf0d0a06786bcbc96c
GOOD LUCK!

**Comment by blwhite13** [comment]
re

**Comment by radilov085** [comment]
[!] error: wifite must be run as root
 [!] re-run with sudo
Help me with such a mistake what to do?

**Comment by bunnyz37** [comment]
> [!] erreur: wifite doit être exécuté en tant que root > [!] re-run avec sudo > Aidez-moi avec une telle erreur, que faire ? 
jai le meme problème

**Comment by dpu4kwje7957** [comment]
这是来自QQ邮箱的假期自动回复邮件。

**Comment by bunnyz37** [comment]
???

**Comment by amiralikhosheh13-create** [comment]
> [!] ERROR: wifite must be run as root [!] login as root (su root) or try sudo ./wifite.py
> 
> ✘  ~/wifite   master  sudo python2 wifite.py Failed to execute process '/data/data/com.termux/files/usr/bin/sudo'. Reason: exec: Exec format error The file '/data/data/com.termux/files/usr/bin/sudo' is marked as an executable but could not be run by the operating system.
