### ISSUE TITLE
please clarify versioning

### ISSUE THREAD

**Issue by blshkv** [derv82/wifite#130]
Check this out:
https://repology.org/metapackage/wifite/versions there is a big confusion and all distros come up with their understanding.

Older versions (hosted at google) used to be " v2.0 r85". Based on the latest commit (https://github.com/derv82/wifite/commit/46abcbe4db8e38e4bfd75cbd4aa5e708e6412750) it is "r88"

Could you please release a version (v1) with a standard versioning structure and keep it this way?

**Comment by derv82** [comment]
*Disclosure: This repo is a mess.*

The reason I changed the major version in this repo to `V1` is to differentiate it from https://github.com/derv82/wifite2 (newer, recommended version -- total rewrite of this repo).

But I can see why this is confusing.

The `rXX` versioning doesn't help either; that is an artifact left over from when I started this project on Google Code.

-------

Here's the different kinds of revisions I see on [repology](https://repology.org/metapackage/wifite/versions):

* `135` (not sure where this came from)
* `v2.0r85`
* `v2.0.85[...]`
* `87.r139[...]`

Looks like `v2.0` is commonly used, along with the `rXX`. Specifically Debian considers the versioning `2.0.87.git2017...` so I'll focus on fixing the Debian versioning at least.

Here's my plan:

1. I will revert this repo back to `v2.0` and up the revision to `r89`.
   * This will match the existing repo versioning in at least a few systems like Debian. E.g. `2.0.89` or `2.0r89`
   * This is **definitely** better than `v1.0`
   * I will create a "release" in this repo for `2.0.89` to coerce people to use that versioning system. (Edit: [done](https://github.com/derv82/wifite/releases/tag/2.0.89))
2.  I will change the newer "wifite2" repo to `v2.1` to differentiate it from this repo.  
    * I will also create a `v2.1.0` release on the new repo, to coerce that versioning system.

I don't plan on making any other changes to this repo, other than severe bug/security fixes. So hopefully this will resolve the versioning issue/confusion.

Feel free to create an issue in [the new repo](https://github.com/derv82/wifite2/issues) to suggest a versioning system in the new system. I was going to go with `2.<major>.<minor>` but I'm open to new ideas.

**Comment by blshkv** [comment]
Thanks, that will do it.

Also, ```wifite2``` is a different tool formally so its name versioning can start from 1.
But I suspect you want it to be a next *ng* version. So you could host it here as well, just under a different branch, something similar to https://github.com/aquynh/capstone/tree/next.

But it it might be complicated and it's your call ;-)

Cheers!

**Comment by anthraxx** [comment]
@derv82 even if wifite2 is a complete rewrite, its the very same tool. wouldn't it still make sense to maintain both in the very same repo with different branches?
bettercap f.e. made a full rewrite in go and its still the very same repo, its just totally confusing to split it up like this. different version schema should be sufficient to distinguise between different major versions of the same tool.

**Comment by blshkv** [comment]
that's exactly what I was trying to say. Thank you to make it clear

**Comment by derv82** [comment]
I outlined the reasons why it would be good to move the new version to this repo on a separate branch.

My favorite reason is I get to resolve all issues & pull requests that are regarding the old version! 😈
