### ISSUE TITLE
Don't have /hs directory

### ISSUE THREAD

**Issue by Craigkelly1992** [derv82/wifite#42]
My handshakes are supposed to be being saved under /hs/... but I don't have this file, or the other ones that are used to save with (like captures). Any idea as to what I can do or why this is happening? Search fails to find any of these files either.

Weird thing is wifite still remembers that I have gotten successful cracks and handshakes

**Comment by aanarchyy** [comment]
Not really sure, this is part of wifite that i didn't write.  I'll look into it though.

**Comment by mcranford13** [comment]
You need to navigate to /root/hs

**Comment by derv82** [comment]
The `/hs/` directory is actually `./hs/` -- should be inside the same directory that you ran Wifite.

**Comment by ruzlicali16** [comment]
Where can i found the /hs. or ./hs/ directory? Please help!!!
