### ISSUE TITLE
Wrongly detected channel support [it's part of aircrack-ng] a.k.a --ignore-negative-one option needed for unpatched cfg80211 !

### ISSUE THREAD

**Issue by AreYouLoco** [derv82/wifite#45]
Hello World!

PROBLEM: For some drivers like b43 (Network controller: Broadcom Corporation BCM4312 802.11b/g LP-PHY (rev 01)) there is a exception that when you try to run monitor mode on interface. AirCrack detects channel as -1. Also later when working with aireplay-ng it may result in fake authentication failure because of that.

EXPLANATION: It's related to one patch for driver that not all versions have. It's not really fatal if you do some steps in correct order. Injection should work anyway without problems.
!AIRMON-NG: usage: airmon-ng <start|stop|check> <interface> [channel or frequency]
!AIREPLAY-NG: --ignore-negative-one : if the interface's channel can't be determined, ignore the mismatch, needed for unpatched cfg80211

SOLUTION: ...is to start airmon-ng with specifying some particular channel (for example like this: sudo airmon-ng start wlan0 6) and do that only once so the instances of monitor card are not multiplied ( see: #30 ) . AND to use --ignore-negative-one option provided in aireplay-ng.

IMPLEMENTATION:
$.difficulty.medium. possibility to check if there is a monitor already running on interface to avoid duplication if there is one already (see: #30 ). IDK maybe by checking if there is a interface which name fits pattern "mon*" (I am not sure if all the monitor interfaces all named like this or maybe some more reliable way for example iwconfig and checking the Mode: for each interface )
     sudo iwconfig
wlan0     [...] Mode:Managed [...]
mon0     [...] Mode:Monitor [...]
eth0      no wireless extensions.

$.difficulty.medium. to kill all processes that might make troubles. YES ALL OF THEM if you want to crack the network you don't need them at this time focus on important stuff.
so for me it will be:
     sudo airmon-ng check wlan0
$.difficulty.easy. possibility to specify channel to start monitor on !
-c CHANNEL            Channel to scan for targets AND RUN MONITOR ON.
$.difficulty.easy. implementation of --ignore-negative-one from aireplay-ng [aircrack-ng].

That's all I wanted to say and THX for the nice tool developers.

**Comment by AreYouLoco** [comment]
If nobody will attempt to implement that I will look at the code but I have to admit that I am just script kiddie and I have no experience with python at all. So it will take me a lot of time to do that. Which actually I don't have a lot. I am more like fighting for survival at the moment.

**Comment by derv82** [comment]
The code already uses `iwconfig` to detect devices in `Mode:Monitor`: https://github.com/derv82/wifite/blob/30dcc8d99223f8e5faa2f9fa62ab8f392b2d4c67/wifite.py#L969-L980

And all `aireplay-ng` commands include the `--ignore-negative-one` argument.

I do think there's value in initializing the monitor interface on the channel specified by `-c`.

**Comment by AreYouLoco** [comment]
There is. SImply specify channel at the end of command.
# man airmon-ng

NAME
       airmon-ng  -  bash  script designed to turn wireless cards into
monitor
       mode.

SYNOPSIS
       airmon-ng <start|stop> <interface> [channel] airmon-ng <check> [kill]

so for example with my configuration:
        sudo airmon-ng start wlan0 6

W dniu 25.05.2015 o 20:58, derv pisze:
>
> The code already uses |iwconfig| to detect devices in |Mode:Monitor|:
> https://github.com/derv82/wifite/blob/30dcc8d99223f8e5faa2f9fa62ab8f392b2d4c67/wifite.py#L969-L980
>
> And all |aireplay-ng| commands include the |--ignore-negative-one|
> argument.
>
> I do think there's value in initializing the monitor interface on the
> channel specified by |-c|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/derv82/wifite/issues/45#issuecomment-105289228>.
>


--
