### ISSUE TITLE
Crack.txt

### ISSUE THREAD

**Issue by Darkcast** [derv82/wifite#5]
Then the program finish cracking the ap 
the it creates a file called cracked.txt
and none of the linux application i have 
installed is able to open it because of invalid characters

**Comment by HENDRA1211** [comment]
Mana akun yg kena crak token

**Comment by 0114609511** [comment]
ا

في السبت، ٢٤ يوليو ٢٠٢١ ١:٥٦ م HENDRA1211 ***@***.***> كتب:
