### ISSUE TITLE
it enables monitor mode on a active monitor

### ISSUE THREAD

**Issue by Ian321** [derv82/wifite#62]
[+] scanning for wireless devices...
[+] enabling monitor mode on wlan0... done
[+] enabling monitor mode on wlan0mon... done
[+] enabling monitor mode on wlan0monmon... done
[+] enabling monitor mode on wlan0monmonmon... done
[!] no wireless interfaces were found.
[!] you need to plug in a wifi device or install drivers.

[+] quitting

**Comment by nik16** [comment]
same problem.

**Comment by youvee** [comment]
same issue.

**Comment by ilfuriano** [comment]
same issue

**Comment by tomtox** [comment]
If you know more please contact me....thx
Am 02.12.2015 08:47 schrieb "ilfuriano" <notifications@github.com>:

**Comment by Ian321** [comment]
a small workaround:
row 225
 # User-defined interface already in monitor mode
