### ISSUE TITLE
wifite stuck on enabling monitor mode on wlan0

### ISSUE THREAD

**Issue by konsbn** [derv82/wifite#71]
![screenshot from 2015-12-28 03 35 07](https://cloud.githubusercontent.com/assets/3414469/12012305/22a037c6-ad14-11e5-8ae6-08d776f640b1.png)

**Comment by Ian321** [comment]
a small workaround:
row 225
# User-defined interface already in monitor mode

**Comment by ChrisFernandez** [comment]
I'm having the same issue in arch Linux. what about a fix instead of a work around?

**Comment by WilsonBradley** [comment]
Same problem here.. 
Not clear with top instruction. 
Should this be changed?
  self.MONITOR_IFACE = ''  # User-defined interface already in monitor mode

**Comment by AllanDenis** [comment]
My branch has a fix for this: https://github.com/AllanDenis/wifite/tree/develop

**Comment by Knightcrawler-Owl** [comment]
Hi all,

I figured out a way to skip this step. Basically you need to enable monitor mode before wifite.

`airmon-ng start [iface]`

and then

`wifite`

In my case this method forces wifite to skip monitor mode loop. 

Cheers,
Owl

**Comment by Drosos2000** [comment]
Enable monitor mode to your adapter and then set the Interface in wifite directly:
airmon-ng start MONITOR_INTERFACE
wifite --mon-iface MONITOR_INTERFACE

For example:
airmon-ng start wlan1
wifite --mon-iface wlan1mon

**Comment by Shahzod111** [comment]
hello everyone help me show prism0

root@kali:~# airmon-ng start wlan0

Found 4 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

  PID Name
  487 NetworkManager
  543 wpa_supplicant
 3948 dhclient
 3992 dhclient

PHY	Interface	Driver		Chipset

phy0	wlan0		wl		Broadcom Limited BCM43142 802.11b/g/n (rev 01)

		(experimental wl monitor mode vif already enabled for [phy0]wlan0 on [phy0]prism0)

**Comment by gurinderpathan** [comment]
root@localhost:~# airmon-ng

ls: cannot access '/sys/class/net': No such file or directory
PHY     Interface       Driver          Chipset

null    Bit             ??????          non-mac80211 device? (report this!)
null    Channel:0       ??????          non-mac80211 device? (report this!)
null    Mode:Unknown/bug        ??????          non-mac80211 device? (report this!)
null    Rate=-391576    ??????          non-mac80211 device? (report this!)
null    ccmni-lan       ??????          non-mac80211 device? (report this!)
null    ccmni0          ??????          non-mac80211 device? (report this!)
null    ccmni1          ??????          non-mac80211 device? (report this!)
null    ccmni10         ??????          non-mac80211 device? (report this!)
null    ccmni11         ??????          non-mac80211 device? (report this!)
null    ccmni12         ??????          non-mac80211 device? (report this!)
null    ccmni13         ??????          non-mac80211 device? (report this!)
null    ccmni14         ??????          non-mac80211 device? (report this!)
null    ccmni15         ??????          non-mac80211 device? (report this!)
null    ccmni16         ??????          non-mac80211 device? (report this!)
null    ccmni17         ??????          non-mac80211 device? (report this!)
null    ccmni18         ??????          non-mac80211 device? (report this!)
null    ccmni19         ??????          non-mac80211 device? (report this!)
null    ccmni2          ??????          non-mac80211 device? (report this!)
null    ccmni20         ??????          non-mac80211 device? (report this!)
null    ccmni3          ??????          non-mac80211 device? (report this!)
null    ccmni4          ??????          non-mac80211 device? (report this!)
null    ccmni5          ??????          non-mac80211 device? (report this!)
null    ccmni6          ??????          non-mac80211 device? (report this!)
null    ccmni7          ??????          non-mac80211 device? (report this!)
null    ccmni8          ??????          non-mac80211 device? (report this!)
null    ccmni9          ??????          non-mac80211 device? (report this!)
null    kb/s            ??????          non-mac80211 device? (report this!)
null    wlan0           ??????          non-mac80211 device? (report this!)

**Comment by gurinderpathan** [comment]
soluyion this kalinethunter
