### ISSUE TITLE
failed to install aircrack-ng

### ISSUE THREAD

**Issue by scramme** [derv82/wifite#99]
I have just downloaded wifite. It said:

 [!] required program not found: aircrack-ng
 [!] this program is bundled with the aircrack-ng suite:
 [!]        http://www.aircrack-ng.org/
 [!] or: sudo apt-get install aircrack-ng

when I try to install aircrack-ng, it asks me this:

Need to get 830 kB/1,343 kB of archives.
After this operation, 6,060 kB of additional disk space will be used.
Do you want to continue? [Y/n] y

so I answer yes, after that it gives these errors:

Err http://mirrordirector.raspbian.org/raspbian/ jessie/main ieee-data all 20150531.1~deb8u1
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/i/ieee-data/ieee-data_20150531.1~deb8u1_all.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

what do I have to do?
and sorry for my crappy english

**Comment by d4yz** [comment]
Check out this tutorial to install aircrack-ng on the Raspberry Pi.

**Comment by itdaniher** [comment]
@scramme try an apt-get update first.

**Comment by derv82** [comment]
Problem with aircrack, or the apt command on your OS; not a problem with Wifite.

**Comment by Tefybe** [comment]
Help, wifite : Depends: aircrack-ng but it is not installable
Error: Unable to correct problems, you have held broken packages.
